### ISSUE TITLE
Invalid Notebook

### ISSUE THREAD

**Issue by ud0y** [saiful9379/BanglaASR#1]
The `fine_tune_whisper.ipynb` notebook is showing invalid even if I locally run the file. Can you please provide a valid notebook?

**Comment by saiful9379** [comment]
I have also the same issue. but I have shared with you the blog and the collaboration link.

Blog Link: https://huggingface.co/blog/fine-tune-whisper
Colab ipynb file Link: https://colab.research.google.com/github/sanchit-gandhi/notebooks/blob/main/fine_tune_whisper.ipynb

if need any clarification check the train.py script.
please check example-> fine_tune_whisper.ipynb
