### ISSUE TITLE
RuntimeError: The size of tensor a (500) must match the size of tensor b (448) at non-singleton dimension 1

### ISSUE THREAD

**Issue by fayez94** [saiful9379/BanglaASR#2]
I was trying to use your whisper training pipeline but the following error occurred. 

`RuntimeError: The size of tensor a (500) must match the size of tensor b (448) at non-singleton dimension 1`

This is my colab link: 
**https://colab.research.google.com/drive/1sEmLASQIeB5ptzOAT5yTYQzE-fq5PbL8?usp=sharing**

This is my sample Dataset:
Audio:
**https://drive.google.com/drive/folders/1KMSY-M2v_V-lmNzoDRcDrR--FEsejQ_Y?usp=drive_link**
Text:
**https://drive.google.com/file/d/1i07qZ-dexEcenffvReW1_ISf20dModGr/view?usp=drive_link**

**Comment by saiful9379** [comment]
You have used, 
```
model_path = "bangla-speech-processing/BanglaASR"
model = WhisperForConditionalGeneration.from_pretrained(model_path) 

```

means "bangla-speech-processing/BanglaASR" model on the other hand use a feature
extractor or other pre-train model used

 ```openai/whisper-medium```. 

so check the notebook restart again to make sure the pre-train model.

Because "bangla-speech-processing/BanglaASR" trains on a small version model and you want to use ```openai medium model``` .

**Comment by fayez94** [comment]
I have resolved this error by changing some code inside the prepare dataset function. Code is given below,

```
def prepare_dataset(batch):
    MAX_DURATION_IN_SECONDS = 30
    max_input_length = MAX_DURATION_IN_SECONDS * 16000
    speech_array, sampling_rate = torchaudio.load(batch["path"], format="wav")
    array = speech_array[0].numpy()
    batch["array"] = librosa.resample(np.asarray(array), orig_sr=sampling_rate, target_sr=16000)
    batch["sampling_rate"] = 16000
    batch["input_features"] = feature_extractor(batch["array"], 
                                                sampling_rate=batch["sampling_rate"],
                                                max_length=max_input_length).input_features[0]

    batch["labels"] = tokenizer(batch["Text"], 
                                truncation=True,
                                max_length=448).input_ids
    return batch
```

I have found this code in [this discussion](https://discuss.huggingface.co/t/trainer-runtimeerror-the-size-of-tensor-a-462-must-match-the-size-of-tensor-b-448-at-non-singleton-dimension-1/26010/3)
